export const failingReasons = [
  'Grammar/sentence agreement',
  'Didn’t answer questions well on CS Quiz (Quality of addressing concerns)',
  'No CS XP/No relevant XP',
  'Less than 1 year of CS XP',
  'Not Looking for Full-Time Positions',
  'Internet Speed Test - Does Not Meet Requirements',
  'Commitments',
  'Re-applied with 90 days',
  'Responses copied and pasted from external sources',
  'No Failed Screening Email',
  'Ineligible For Wise',
  'Skills Assessment Score Not Met',
  'Creative Portfolio Not Suitable',
  'Less than 1 year of CGA XP',
  'Less than 1 year of AGA XP',
  'No Relevant AGA XP',
  'No Relevant CGA XP',
]
